<?php

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function tinymce_mcimagemanager_wysiwyg_plugin($editor, $version) {
	switch ($editor) {
		case 'tinymce':
			return array(
				'imagemanager' => array(
					'path' => libraries_get_path('imagemanager'),
			  	'filename' => 'editor_plugin.js',
					'buttons' => array('insertimage' => t('MCImageManager')),
					'url' => 'http://wiki.moxiecode.com/index.php/MCImageManager:Index',
					'load' => TRUE
				)
			);
		break;
	}
}

/**
 * implementation hook_permission()
 */
function tinymce_mcimagemanager_permission() {
  return array(
    'access tinymce imagemanager' => array(
      'title' => t('Access TinyMCE MCimagemanager module'), 
    ),
  );
}